name: Apply terraform resources

on:
  push:
    branches:
      - main
         
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  apply:
    name: 'terraform apply'
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: 'terraform'

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.6

      - name: Terraform Init
        id: init
        run: terraform init 

      - name: Terraform Apply
        run: terraform apply -auto-approve 